### ISSUE TITLE
sign_with_library_version has been deprecated

### ISSUE THREAD

**Issue by saschametz** [pancentric/django-imgix#12]
I'm getting the following deprecation warning:
```DeprecationWarning: `sign_with_library_version` has been deprecated and will be removed in the next major version. Use `include_library_param` instead.```

**Comment by lexmiln** [comment]
I was unable to use the tag in my Django application without an exception being thrown because of this deprecation. I fixed it by requiring an imgix version of less than 3.0.0 in my `requirements.txt` (`django-imgix` only constrains `imgix` to `>=1.0.0`):

```
# requirements.txt
django-imgix==1.1.0
imgix<3.0.0 # imgix 3.0.0 deprecates an argument, breaking django-imgix 1.1.0
```
