### ISSUE TITLE
django-imgix! 😁

### ISSUE THREAD

**Issue by paulstraw** [pancentric/django-imgix#2]
Hey Pancentric folks! I just caught wind of this library. I'm Paul, Developer Relations at imgix. I wanted to stop by and let you know I'm happy to help answer any questions you have, or lend a hand with the library if you'd like. Just let me know how I can help.

If you're interested, we'd also be happy to pull this into the https://github.com/imgix organization, and make it an official library. Of course, you'd retain admin access if we went this route. Either way is fine by us, but I wanted to make sure you had the option.

Anyhow, it'd be great to get this listed as an available library on https://www.imgix.com/docs/libraries and in https://github.com/imgix/imgix-blueprint. If that's good by you, I'll go ahead and get it added to those.

**Comment by ajcurated** [comment]
Hi Paul,

Thanks for noticing out module. We would be more than happy to have it listed on your libraries page, however we would like to keep it under our namespace if that's ok with you. 

If you have any suggestions or changes in mind please let us know / open an issue!

Cheers

Alex

**Comment by paulstraw** [comment]
That's totally okay! Just wanted to make sure I offered. If you ever have any questions etc., feel free to @paulstraw me. We've also got an imgix community Slack set up where you can hang out/ask questions, if that's your cup of tea: slack.imgix.com

I'll get this linked in our docs and then close this issue!

-paul
