### ISSUE TITLE
Documentation bug : IMGIX_HTTPS defaults to True

### ISSUE THREAD

**Issue by hchargois** [pancentric/django-imgix#4]
It says in the README that IMGIX_HTTPS defaults to False but this is not True ;)

https://github.com/pancentric/django-imgix/blob/master/django_imgix/templatetags/imgix_tags.py#L38

**Comment by ajcurated** [comment]
Thanks @hchargois we'll get this fixed ASAP

**Comment by luqven** [comment]
This is probably some sort of record 😆 

Seems like this issue is resolved. If there are any further issues please feel free to comment and I'll be sure to re-open it.
