### ISSUE TITLE
Support multiple sources

### ISSUE THREAD

**Issue by ssbb** [pancentric/django-imgix#5]
Hi! Thank you for this awesome work.

I just imagine if it possible to use multiple sources. It is not possible now because there is no way to override settings (or at least `domains`) in template tag function.

**Comment by luqven** [comment]
Wow, it's uh, taken us a bit to get back to you 😬 ...

Thanks for the suggestion. Since there hasn't been any movement on this issue I'm going to go ahead and close it for now. Please comment if there are any further issues and I'll be sure to re-open it
